version: '3'

services:

 petshop-db:
   image: postgres:latest
   container_name: petshop-db
   networks:
     - petshop
   environment:
     - POSTGRES_DB=petshop_db
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   ports:
     - 5433:5432
   volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql


 petshop-backend:
   build: ./petshop-backend
   container_name: petshop-backend
   depends_on:
     - petshop-db
   networks:
     - petshop
   environment:
     - PORT=8081
     - DB_HOST=petshop-db
     - DB_PORT=5432
     - DB_NAME=petshop_db
     - DB_USERNAME=postgres
     - DB_PASSWORD=postgres
   ports:
     - 8081:8081

 wildfly:
    image: jboss/wildfly:20.0.1.Final
    container_name: wildfly-petshop
    networks:
      - petshop
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - ./petshop-frontend/target/petshop.war:/opt/jboss/wildfly/standalone/deployments/petshop.war
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    command: ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]

networks:
  petshop:
    driver: bridge
