# ========== Configurações da Aplicação Back-end do PetShop ==========

server:
  port: ${PORT:8081}

spring:
  application:
    name: PetShop Metaway


# Banco de dados configurações
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:petshop_metaway}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10


# Flyway configurações
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1


# ActiveMQ configurações
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false


# MyBatis configurações
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml


# LOGS DA APLICAÇÃO
logging:
  level:
    org:
      mybatis: DEBUG
      apache:
        ibatis: DEBUG
logging.level.org.apache.ibatis.cache: DEBUG


# Variáveis de configurações do sistema:
jwt:
  secret: QXBsaWNhw6fDo28gcGFyYSBhIG1ldGF3YXkgKFRlc3RlKSAtIFBldFNob3A=